### ISSUE TITLE
Feature proposal: Resolve actual version for RELEASE or LATEST (code attached)

### ISSUE THREAD

**Issue by nicymike** [mihxil/ansible-nexus#8]
Hello.

Thank you for your work on this module. I'm using it to deploy artifacts for development with version LATEST. But since I need the actual version for the artifact, I changed your code to do that (see attached file). You may use the code to extend your module.

I am not a python expert but the code works with nexus server 2.11.4.

Kind regards
Michael

[nexus.zip](https://github.com/mihxil/ansible-nexus/files/803698/nexus.zip)

**Comment by gilesw** [comment]
Hi Nicymike,

It seems like I added the feature myself without seeing your patch! Oh well it's been merged into master now.

**Comment by nicymike** [comment]
Very nice. Thank you.
